#the docker compose file version
version: "2"
# you can run multiple services inside one docker compose file
# define them with their dependencies one after the other
services:
  # service 1 named react-prod
  maintenance-page:
    # service 1 container name
    container_name: maintenance-page
    build:
      # the context (working directory) is the current directory
      # change this to the directory containing the dockerfile if in a different place
      context: .
      # the dockerfile to be run
      dockerfile:
        Dockerfile
        # map the exposed port from the underlying service to a port exposed to the outside
        # in this case  map port 80 exposed by nginx to port 3000 on the outside
        # to be used to access the container from the outside
    ports:
      - "80:80"
      - "443:443"
    networks:
      - ayr-user-network
    volumes:
      - /home/core/mobicascais-project/certificados-mobiresidents/certs:/etc/nginx/certs

networks:
  ayr-user-network:
    external: true  
  
